import type { SimulationScenario } from "./types";

export const SEED_SCENARIOS: SimulationScenario[] = [
  // ── RESTAURANTS ────────────────────────────────────────────────────────────
  {
    id: "restaurant_sushi_objection",
    agentId: "sdr",
    name: "Restaurante Japonês — Objeção de Preço",
    segment: "restaurante",
    difficulty: "hard",
    persona: "Marina — dona de restaurante japonês, desconfiada com marketing",
    initialMessage:
      "Oi, me chamo Marina e tenho um restaurante japonês. Quero social media mas não sei bem o que preciso.",
    personaAnswers: {
      identity:  "Marina Alves, Restaurante Japonês",
      email:     "marina@restaurante.com.br",
      phone:     "11987654321",
      service:   "Quero principalmente Instagram, fotos dos pratos e promoções",
      frequency: "3 vezes por semana no feed",
      budget:    "meu limite é R$ 1.500 por mês",
      objective: "quero mais clientes no jantar e mais pedidos de delivery",
      traffic:   "não quero tráfego pago por enquanto",
      branding:  "já tenho logo, não preciso de identidade visual",
      default:   "pode me explicar melhor?",
    },
    expectedBehaviors: ["ask_restaurant_frequency", "ask_budget", "handle_price_objection", "negotiate_scope"],
    objectionTypes:    ["price_too_high"],
    budgetRange:       { min: 1500, max: 1500 },
    targetServices:    ["social_media"],
    objectionMessage:  "tá caro demais, meu limite é R$ 1.500",
    objectionAfterTurn: 4,
    acceptanceMessage: "pode ser, vamos com o plano starter",
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "restaurant_pizza_low_budget",
    agentId: "sdr",
    name: "Pizzaria São Paulo — Budget Baixo",
    segment: "restaurante",
    difficulty: "hard",
    persona: "Marco — dono de pizzaria, quer resultado por R$ 800",
    initialMessage:
      "Olá, me chamo Marco e tenho uma pizzaria chamada Pizza São Paulo. Quero aumentar as vendas nas redes sociais.",
    personaAnswers: {
      identity:  "Marco Rossi, Pizzaria São Paulo",
      email:     "marco@pizzasp.com.br",
      phone:     "11976543210",
      service:   "quero Instagram e Facebook",
      frequency: "2 vezes por semana",
      budget:    "tenho 800 reais por mês",
      objective: "aumentar pedidos de delivery",
      traffic:   "não quero anúncios",
      branding:  "não preciso de logo",
      default:   "não entendi, pode repetir?",
    },
    expectedBehaviors: ["handle_below_minimum_budget", "explain_starter_plan", "adjust_expectation"],
    objectionTypes:    ["price_too_high", "wants_cheaper"],
    budgetRange:       { min: 800, max: 800 },
    targetServices:    ["social_media"],
    objectionMessage:  "800 reais é o máximo que posso gastar",
    objectionAfterTurn: 3,
    acceptanceMessage: "ok, me explica o plano starter então",
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "restaurant_cafe_simple",
    agentId: "sdr",
    name: "Café Boutique — Entrada Simples",
    segment: "café",
    difficulty: "easy",
    persona: "Juliana — dona de café, quer social media simples",
    initialMessage:
      "Oi! Sou a Juliana e tenho um café chamado Café Boutique. Quero social media para o Instagram.",
    personaAnswers: {
      identity:  "Juliana Mendes, Café Boutique",
      email:     "juliana@cafeboutique.com.br",
      phone:     "11965432109",
      service:   "quero Instagram, posts de produtos e ambiente",
      frequency: "4 vezes por semana",
      budget:    "tenho 2 mil por mês",
      objective: "mais clientes presenciais e mais seguidores",
      traffic:   "talvez no futuro",
      branding:  "tenho logo mas posso melhorar",
      default:   "sim, pode continuar",
    },
    expectedBehaviors: ["capture_identity", "ask_frequency", "confirm_budget"],
    objectionTypes:    [],
    budgetRange:       { min: 2000, max: 2000 },
    targetServices:    ["social_media"],
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  // ── BEAUTY ─────────────────────────────────────────────────────────────────
  {
    id: "beauty_manicure_simple",
    agentId: "sdr",
    name: "Estúdio de Manicure — Entrada Simples",
    segment: "beleza",
    difficulty: "easy",
    persona: "Ana — dona de estúdio de manicure",
    initialMessage:
      "Me chamo Ana e tenho um estúdio de manicure. Quero social media para atrair mais clientes.",
    personaAnswers: {
      identity:  "Ana Paula, Studio Ana",
      email:     "ana@studioana.com.br",
      phone:     "11954321098",
      service:   "Instagram principalmente, fotos das unhas",
      frequency: "3 vezes por semana",
      budget:    "1.800 reais",
      objective: "mais agendamentos e clientes novas",
      traffic:   "não por enquanto",
      branding:  "já tenho logo",
      default:   "sim",
    },
    expectedBehaviors: ["capture_identity", "ask_frequency", "confirm_budget"],
    objectionTypes:    [],
    budgetRange:       { min: 1800, max: 1800 },
    targetServices:    ["social_media"],
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "beauty_salon_brand_book",
    agentId: "sdr",
    name: "Salão Premium — Tem Brand Book",
    segment: "beleza",
    difficulty: "medium",
    persona: "Fernanda — dona de salão premium com brand book completo",
    initialMessage:
      "Oi, sou a Fernanda do Salão Fernanda Beauty. Tenho meu manual de marca completo e quero social media profissional.",
    personaAnswers: {
      identity:  "Fernanda Costa, Fernanda Beauty",
      email:     "fernanda@fernandabeauty.com.br",
      phone:     "11943210987",
      service:   "Instagram e TikTok, conteúdo de beleza e transformação",
      frequency: "5 vezes por semana",
      budget:    "3 mil por mês",
      objective: "posicionamento premium e novos clientes de alto ticket",
      traffic:   "quero anúncios também",
      branding:  "já tenho brand book completo, não preciso de identidade",
      default:   "sim, pode prosseguir",
    },
    expectedBehaviors: ["recognize_brand_book_as_asset", "no_branding_suggestion", "ask_frequency", "ask_about_traffic_budget"],
    objectionTypes:    [],
    budgetRange:       { min: 3000, max: 3000 },
    targetServices:    ["social_media", "paid_traffic"],
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "beauty_clinic_unclear",
    agentId: "sdr",
    name: "Estética Corporal — Escopo Confuso",
    segment: "estética",
    difficulty: "hard",
    persona: "Camila — clínica de estética sem clareza do que quer",
    initialMessage:
      "Preciso de marketing digital mas não sei bem o que quero. Tenho uma clínica de estética corporal.",
    personaAnswers: {
      identity:  "Camila Rodrigues, Clínica Camila Estética",
      email:     "camila@clinicacamila.com.br",
      phone:     "11932109876",
      service:   "talvez redes sociais ou anúncios, não sei",
      frequency: "2 ou 3 vezes por semana",
      budget:    "não sei quanto custa, não tenho valor definido",
      objective: "mais clientes para procedimentos estéticos",
      traffic:   "se compensar, sim",
      branding:  "preciso de uma identidade melhor",
      default:   "não tenho certeza, o que você recomenda?",
    },
    expectedBehaviors: ["guide_unclear_client", "ask_objectives_first", "then_services", "qualify_before_pricing"],
    objectionTypes:    ["unsure_budget"],
    budgetRange:       undefined,
    targetServices:    ["social_media"],
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  // ── LOCAL SERVICE ──────────────────────────────────────────────────────────
  {
    id: "local_gym_urgent",
    agentId: "sdr",
    name: "Academia FitMax — Urgência",
    segment: "academia",
    difficulty: "medium",
    persona: "Bruno — dono de academia com urgência de inauguração",
    initialMessage:
      "Olá, sou o Bruno da Academia FitMax. Vou inaugurar em 2 semanas e preciso urgente de redes sociais e divulgação.",
    personaAnswers: {
      identity:  "Bruno Santos, FitMax Academia",
      email:     "bruno@fitmax.com.br",
      phone:     "11921098765",
      service:   "Instagram e Facebook com posts de inauguração",
      frequency: "5 vezes por semana",
      budget:    "2.500 reais",
      objective: "lotar as primeiras turmas de alunos",
      traffic:   "quero anúncios para a inauguração",
      branding:  "tenho logo mas é simples",
      default:   "preciso disso urgente mesmo",
    },
    expectedBehaviors: ["address_urgency", "ask_scope_within_timeline", "handle_deadline_pressure"],
    objectionTypes:    ["deadline_pressure"],
    budgetRange:       { min: 2500, max: 2500 },
    targetServices:    ["social_media", "paid_traffic"],
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "local_petshop_cheap",
    agentId: "sdr",
    name: "Pet Shop Rodrigo — Quer Tudo Barato",
    segment: "pet shop",
    difficulty: "hard",
    persona: "Rodrigo — pet shop que quer tudo ao mesmo tempo pelo menor preço",
    initialMessage:
      "Sou o Rodrigo do Pet Shop Rodrigo. Quero social media, anúncios e identidade visual tudo junto pelo melhor preço.",
    personaAnswers: {
      identity:  "Rodrigo Lima, Pet Shop Rodrigo",
      email:     "rodrigo@petshoprodrigo.com.br",
      phone:     "11910987654",
      service:   "quero tudo que vocês oferecem",
      frequency: "4 vezes por semana",
      budget:    "1.200 reais pra tudo",
      objective: "mais clientes e mais vendas",
      traffic:   "sim, quero anúncios",
      branding:  "quero logo e identidade nova",
      default:   "tudo pelo menor preço",
    },
    expectedBehaviors: ["scope_trim", "prioritize_services", "explain_tradeoffs", "handle_price_objection"],
    objectionTypes:    ["price_too_high", "wants_cheaper"],
    budgetRange:       { min: 1200, max: 1200 },
    targetServices:    ["social_media", "paid_traffic", "branding"],
    objectionMessage:  "1.200 reais é o máximo, precisa caber tudo isso",
    objectionAfterTurn: 4,
    acceptanceMessage: "ok, prioriza o social media então",
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "local_mechanic_no_materials",
    agentId: "sdr",
    name: "Carlos Auto — Sem Materiais",
    segment: "mecânica",
    difficulty: "medium",
    persona: "Carlos — mecânico sem fotos nem materiais de marketing",
    initialMessage:
      "Oi, sou Carlos da Oficina Carlos Auto. Quero Instagram mas não tenho fotos, vídeos nem nada.",
    personaAnswers: {
      identity:  "Carlos Ferreira, Carlos Auto",
      email:     "carlos@carlosauto.com.br",
      phone:     "11909876543",
      service:   "Instagram, posts do dia a dia da oficina",
      frequency: "3 vezes por semana",
      budget:    "1.500 reais",
      objective: "mais clientes na região",
      traffic:   "não",
      branding:  "não tenho logo",
      default:   "pode me ajudar com isso?",
    },
    expectedBehaviors: ["ask_about_material_availability", "explain_photo_cost"],
    objectionTypes:    [],
    budgetRange:       { min: 1500, max: 1500 },
    targetServices:    ["social_media"],
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  // ── SAAS / TECH ────────────────────────────────────────────────────────────
  {
    id: "saas_b2b_social_identity",
    agentId: "sdr",
    name: "GestãoPro — Social + Identidade Visual",
    segment: "SaaS",
    difficulty: "medium",
    persona: "Rafael — founder de software B2B",
    initialMessage:
      "Me chamo Rafael e tenho um software de gestão para pequenas empresas. Quero redes sociais e uma identidade visual mais profissional.",
    personaAnswers: {
      identity:  "Rafael Mendes, GestãoPro",
      email:     "rafael@gestaopro.com.br",
      phone:     "11898765432",
      service:   "LinkedIn e Instagram para B2B",
      frequency: "3 vezes por semana",
      budget:    "3.500 reais",
      objective: "mais leads qualificados e posicionamento como autoridade",
      traffic:   "quero anúncios no LinkedIn",
      branding:  "quero nova identidade visual, a atual está datada",
      default:   "sim, faz sentido",
    },
    expectedBehaviors: ["capture_b2b_context", "scope_branding_separately"],
    objectionTypes:    [],
    budgetRange:       { min: 3500, max: 3500 },
    targetServices:    ["social_media", "paid_traffic", "branding"],
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "tech_delivery_no_media_budget",
    agentId: "sdr",
    name: "DeliveryFácil — Tráfego sem Budget de Mídia",
    segment: "tech",
    difficulty: "hard",
    persona: "Diego — fundador de app de delivery, confunde gestão com budget de mídia",
    initialMessage:
      "Sou o Diego do DeliveryFácil. Quero anúncios para atrair mais restaurantes para o meu app.",
    personaAnswers: {
      identity:  "Diego Alves, DeliveryFácil",
      email:     "diego@deliveryfacil.com.br",
      phone:     "11887654321",
      service:   "quero anúncios no Google e Facebook",
      frequency: "não se aplica",
      budget:    "2.000 reais pra tudo incluindo os anúncios",
      objective: "cadastrar 50 restaurantes no app",
      traffic:   "sim, anúncios são meu foco",
      branding:  "já tenho identidade",
      default:   "pode explicar como funciona?",
    },
    expectedBehaviors: ["separate_media_budget_from_management", "qualify_traffic_budget"],
    objectionTypes:    ["unsure_budget"],
    budgetRange:       { min: 2000, max: 2000 },
    targetServices:    ["paid_traffic"],
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "edtech_unclear_scope",
    agentId: "sdr",
    name: "AprendeMais — Expectativas Irreais",
    segment: "educação",
    difficulty: "extreme",
    persona: "Mariana — fundadora de plataforma EdTech com expectativas muito altas",
    initialMessage:
      "Sou a Mariana da AprendeMais. Quero dominar o marketing digital, virar referência no setor e vender muito.",
    personaAnswers: {
      identity:  "Mariana Oliveira, AprendeMais",
      email:     "mariana@aprendemais.com.br",
      phone:     "11876543210",
      service:   "social media, anúncios e tudo mais que precisar",
      frequency: "todo dia",
      budget:    "não sei, quanto custa essa estratégia toda?",
      objective: "ser líder de mercado em educação online",
      traffic:   "sim, muito tráfego",
      branding:  "quero rebranding completo",
      default:   "não sei, você é o especialista",
    },
    expectedBehaviors: ["guide_high_expectation_client", "prioritize_services", "ask_budget_before_scoping"],
    objectionTypes:    ["unsure_budget"],
    budgetRange:       undefined,
    targetServices:    ["social_media", "paid_traffic", "branding"],
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  // ── ECOMMERCE ──────────────────────────────────────────────────────────────
  {
    id: "ecommerce_fashion_social_needs_campaign",
    agentId: "sdr",
    name: "Patrícia Moda — Pede Social mas Precisa de Campanha",
    segment: "moda",
    difficulty: "medium",
    persona: "Patricia — lojista que quer social media mas o problema real é vendas online",
    initialMessage:
      "Oi, me chamo Patricia da Loja Patrícia Moda. Quero melhorar meu Instagram.",
    personaAnswers: {
      identity:  "Patrícia Souza, Patrícia Moda",
      email:     "patricia@patriciamodas.com.br",
      phone:     "11865432109",
      service:   "Instagram bonito com fotos das roupas",
      frequency: "5 vezes por semana",
      budget:    "2.000 reais",
      objective: "aumentar as vendas da loja online",
      traffic:   "não sabia que existia isso, pode explicar?",
      branding:  "já tenho logo",
      default:   "não entendi muito bem",
    },
    expectedBehaviors: ["detect_real_objective_is_sales", "suggest_paid_traffic", "educate_before_closing"],
    objectionTypes:    [],
    budgetRange:       { min: 2000, max: 2000 },
    targetServices:    ["social_media", "paid_traffic"],
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "ecommerce_artisan_low_budget",
    agentId: "sdr",
    name: "Arte da Bea — Budget Muito Baixo",
    segment: "ecommerce",
    difficulty: "hard",
    persona: "Beatriz — artesã que vende online, budget abaixo do mínimo",
    initialMessage:
      "Sou a Beatriz e vendo artesanato pelo Instagram. Quero crescer mais.",
    personaAnswers: {
      identity:  "Beatriz Ferreira, Arte da Bea",
      email:     "bea@artedabea.com.br",
      phone:     "11854321098",
      service:   "Instagram mais profissional",
      frequency: "2 vezes por semana",
      budget:    "600 reais por mês",
      objective: "vender mais peças e crescer no Instagram",
      traffic:   "não tenho dinheiro pra isso",
      branding:  "não",
      default:   "sim",
    },
    expectedBehaviors: ["handle_below_minimum_budget", "explain_starter_plan", "suggest_alternatives"],
    objectionTypes:    ["price_too_high", "wants_cheaper"],
    budgetRange:       { min: 600, max: 600 },
    targetServices:    ["social_media"],
    objectionMessage:  "600 reais é tudo que tenho",
    objectionAfterTurn: 3,
    acceptanceMessage: "ok, entendo. o que vocês podem fazer?",
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "ecommerce_electronics_branding_no_budget",
    agentId: "sdr",
    name: "TechStore — Pede Branding sem Budget",
    segment: "ecommerce",
    difficulty: "extreme",
    persona: "Thiago — lojista de eletrônicos que quer identidade visual sem orçamento adequado",
    initialMessage:
      "Sou o Thiago da TechStore e quero uma identidade visual nova e profissional para minha loja.",
    personaAnswers: {
      identity:  "Thiago Lima, TechStore",
      email:     "thiago@techstoresp.com.br",
      phone:     "11843210987",
      service:   "identidade visual completa",
      frequency: "não se aplica",
      budget:    "800 reais para tudo",
      objective: "parecer uma marca grande e profissional",
      traffic:   "quero também anúncios",
      branding:  "nova identidade visual completa",
      default:   "sim mas quero barato",
    },
    expectedBehaviors: ["explain_branding_investment", "handle_budget_mismatch"],
    objectionTypes:    ["price_too_high", "wants_cheaper"],
    budgetRange:       { min: 800, max: 800 },
    targetServices:    ["branding"],
    objectionMessage:  "800 reais é o meu limite para a identidade",
    objectionAfterTurn: 3,
    acceptanceMessage: "tudo bem, o que cabe no meu orçamento?",
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  // ── CLINIC ─────────────────────────────────────────────────────────────────
  {
    id: "clinic_dental_medium",
    agentId: "sdr",
    name: "Clínica Paulo Odonto — Médio Porte",
    segment: "odontologia",
    difficulty: "easy",
    persona: "Dr. Paulo — dentista, quer social media profissional",
    initialMessage:
      "Olá, sou o Dr. Paulo da Clínica Paulo Odonto. Quero redes sociais para atrair mais pacientes.",
    personaAnswers: {
      identity:  "Dr. Paulo Henrique, Clínica Paulo Odonto",
      email:     "paulo@pauloodonto.com.br",
      phone:     "11832109876",
      service:   "Instagram e Facebook com posts educativos",
      frequency: "4 vezes por semana",
      budget:    "2.200 reais",
      objective: "mais pacientes novos por mês",
      traffic:   "quero anúncios para captação",
      branding:  "tenho logo mas pode melhorar",
      default:   "sim",
    },
    expectedBehaviors: ["capture_identity", "ask_frequency", "ask_traffic_budget"],
    objectionTypes:    [],
    budgetRange:       { min: 2200, max: 2200 },
    targetServices:    ["social_media", "paid_traffic"],
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "clinic_psychologist_online",
    agentId: "sdr",
    name: "Dra. Laura — Psicóloga Online",
    segment: "saúde mental",
    difficulty: "easy",
    persona: "Dra. Laura — psicóloga online, foco em Instagram",
    initialMessage:
      "Oi! Sou a Dra. Laura, psicóloga que atende online. Preciso de ajuda com meu Instagram.",
    personaAnswers: {
      identity:  "Dra. Laura Silva, Consultório Online",
      email:     "laura@laurapsico.com.br",
      phone:     "11821098765",
      service:   "Instagram com conteúdo educativo sobre saúde mental",
      frequency: "3 vezes por semana",
      budget:    "1.800 reais",
      objective: "mais seguidores e mais pacientes online",
      traffic:   "não por enquanto",
      branding:  "já tenho logo",
      default:   "sim",
    },
    expectedBehaviors: ["capture_identity", "ask_frequency", "confirm_budget"],
    objectionTypes:    [],
    budgetRange:       { min: 1800, max: 1800 },
    targetServices:    ["social_media"],
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "clinic_aesthetics_traffic",
    agentId: "sdr",
    name: "Clínica Renata Estética — Tráfego Pago",
    segment: "estética",
    difficulty: "medium",
    persona: "Dra. Renata — clínica de estética que quer tráfego pago",
    initialMessage:
      "Sou a Dra. Renata da Clínica Renata Estética. Quero anúncios para atrair mais clientes para botox e harmonização.",
    personaAnswers: {
      identity:  "Dra. Renata Costa, Clínica Renata Estética",
      email:     "renata@renastaeste.com.br",
      phone:     "11810987654",
      service:   "anúncios no Facebook e Instagram",
      frequency: "não se aplica",
      budget:    "3.000 mais 1.500 de mídia",
      objective: "agendar 30 consultas novas por mês",
      traffic:   "sim, tráfego pago é prioridade",
      branding:  "já tenho marca",
      default:   "sim",
    },
    expectedBehaviors: ["separate_media_budget", "ask_monthly_ad_budget", "capture_traffic_goal"],
    objectionTypes:    [],
    budgetRange:       { min: 3000, max: 4500 },
    targetServices:    ["paid_traffic"],
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  // ── EDUCATION ──────────────────────────────────────────────────────────────
  {
    id: "education_languages_social_ads",
    agentId: "sdr",
    name: "André Idiomas — Social + Anúncios",
    segment: "educação",
    difficulty: "medium",
    persona: "André — dono de escola de idiomas",
    initialMessage:
      "Sou o André da Escola de Inglês André. Quero social media e anúncios para matrículas.",
    personaAnswers: {
      identity:  "André Costa, Escola André Idiomas",
      email:     "andre@andreidiomas.com.br",
      phone:     "11800987654",
      service:   "Instagram, Facebook e Google Ads",
      frequency: "4 vezes por semana",
      budget:    "2.800 mais verba de anúncios",
      objective: "50 matrículas novas por semestre",
      traffic:   "sim, anúncios são essenciais",
      branding:  "não preciso de logo",
      default:   "sim",
    },
    expectedBehaviors: ["ask_about_ad_budget", "separate_mgmt_from_media", "qualify_objective"],
    objectionTypes:    [],
    budgetRange:       { min: 2800, max: 4000 },
    targetServices:    ["social_media", "paid_traffic"],
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "education_online_course_unclear",
    agentId: "sdr",
    name: "Curso Fotografia Lucia — Pontual ou Mensal?",
    segment: "infoproduto",
    difficulty: "hard",
    persona: "Lucia — criadora de curso online, confusa sobre tipo de contrato",
    initialMessage:
      "Sou a Lucia e vou lançar um curso online de fotografia. Quero marketing para o lançamento.",
    personaAnswers: {
      identity:  "Lucia Alves, Curso Fotografia Lucia",
      email:     "lucia@cursosfoto.com.br",
      phone:     "11791098765",
      service:   "social media para o lançamento e anúncios",
      frequency: "todo dia na semana de lançamento",
      budget:    "4.000 para o projeto de lançamento",
      objective: "vender 100 matrículas no primeiro mês",
      traffic:   "sim, anúncios para captação de leads",
      branding:  "já tenho identidade",
      default:   "é uma vez só, o lançamento",
    },
    expectedBehaviors: ["clarify_project_vs_monthly", "scope_launch_as_one_off", "qualify_ad_budget"],
    objectionTypes:    [],
    budgetRange:       { min: 4000, max: 4000 },
    targetServices:    ["social_media", "paid_traffic"],
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  // ── REAL ESTATE ────────────────────────────────────────────────────────────
  {
    id: "realestate_agency_full",
    agentId: "sdr",
    name: "Imobiliária Boa Vista — Escopo Completo",
    segment: "imóveis",
    difficulty: "hard",
    persona: "Roberto — diretor de imobiliária regional, aprovação interna necessária",
    initialMessage:
      "Sou o Roberto da Imobiliária Boa Vista. Quero social media profissional, anúncios e uma nova identidade para a marca.",
    personaAnswers: {
      identity:  "Roberto Campos, Imobiliária Boa Vista",
      email:     "roberto@boavistaimoveis.com.br",
      phone:     "11782109876",
      service:   "Instagram, Facebook, Google Ads e identidade visual",
      frequency: "5 vezes por semana",
      budget:    "6.000 reais mais verba de anúncios",
      objective: "vender 10 imóveis por mês via digital",
      traffic:   "sim, Google Ads e Meta Ads",
      branding:  "quero nova identidade, a atual está velha",
      default:   "sim, vamos fechar",
    },
    expectedBehaviors: ["scope_full_suite", "ask_media_budget", "price_branding_separately"],
    objectionTypes:    ["needs_internal_approval"],
    budgetRange:       { min: 6000, max: 8000 },
    targetServices:    ["social_media", "paid_traffic", "branding"],
    objectionMessage:  "preciso aprovar isso com meu sócio antes de fechar",
    objectionAfterTurn: 6,
    acceptanceMessage: "falei com ele, vamos em frente",
    createdAt: "2026-01-01T00:00:00.000Z",
  },
  {
    id: "realestate_broker_low_budget",
    agentId: "sdr",
    name: "Paulo Corretor — Budget Extremo",
    segment: "imóveis",
    difficulty: "extreme",
    persona: "Paulo — corretor autônomo com budget muito baixo e expectativas altas",
    initialMessage:
      "Oi! Sou o Paulo, corretor de imóveis autônomo. Quero anúncios e social media para vender mais.",
    personaAnswers: {
      identity:  "Paulo Vieira, Paulo Corretor",
      email:     "paulo@paulocorretor.com.br",
      phone:     "11773210987",
      service:   "anúncios e Instagram",
      frequency: "2 vezes por semana",
      budget:    "900 reais pra tudo",
      objective: "fechar 3 vendas por mês pelo digital",
      traffic:   "sim, anúncios",
      branding:  "não",
      default:   "entendi",
    },
    expectedBehaviors: ["handle_below_minimum_budget", "adjust_expectations"],
    objectionTypes:    ["price_too_high", "wants_cheaper"],
    budgetRange:       { min: 900, max: 900 },
    targetServices:    ["social_media", "paid_traffic"],
    objectionMessage:  "900 reais é tudo que consigo pagar",
    objectionAfterTurn: 3,
    acceptanceMessage: "entendi, o que cabe no meu orçamento?",
    createdAt: "2026-01-01T00:00:00.000Z",
  },
];
