// Dioli Brain — Department Definitions
// Departments are professional scopes — not independent brains.
// Brain logic is shared. Departments define:
//   permissions, tools, deliverables, quality gates, evidence types, approval triggers.

import type { BrainDepartment } from "./types";

export const BRAIN_DEPARTMENTS: BrainDepartment[] = [
  {
    id: "client-service-sdr",
    name: "Atendimento / SDR",
    mission:
      "Capturar a intenção real do cliente, qualificar a demanda e fazer o handoff correto para o pipeline de execução.",
    responsibilities: [
      "Receber e qualificar briefings de novos clientes",
      "Conduzir conversação de descoberta via Briefing Room",
      "Identificar escopo, budget e expectativas",
      "Gerar handoff estruturado para PM",
      "Alertar sobre clientes que precisam de atenção imediata",
    ],
    permissions: [
      "Acessar Brand Brain do cliente",
      "Criar e atualizar Briefings",
      "Criar Client Requests",
      "Visualizar histórico do cliente",
      "Gerar estimativa de escopo e proposta inicial",
    ],
    forbiddenActions: [
      "Aprovar entrega sem revisão do cliente",
      "Iniciar produção sem proposta aprovada",
      "Fazer promessas de prazo ou budget sem validação do PM",
      "Modificar Brand Brain sem aprovação",
    ],
    tools: [
      "briefing_room",
      "sdr_agent",
      "prospect_engine",
      "live_calculator",
      "client_history",
    ],
    suggestedAIEngine: "fast_commercial",
    allowedKnowledgeSources: [
      "client_brand_brain",
      "client_profile",
      "briefings",
      "client_requests",
      "training_logs",
    ],
    qualityGate: [
      "Budget do cliente respeitado e separado do management fee",
      "Objeções identificadas e endereçadas",
      "Escopo claro — sem promessas vagas",
      "Nenhuma promessa falsa sobre prazo ou resultado",
      "Management fee separado do budget de mídia",
      "Handoff inclui todos os campos obrigatórios",
    ],
    simulator: "lib/agency/training/runner.ts",
    trainingCenter: "/agency/simulations/training",
    evidenceTypes: [
      "first_round_approval",
      "client_praise",
      "delivery_time_reduction",
    ],
    humanApprovalTriggers: [
      "budget_acima_de_threshold",
      "escopo_customizado_sem_precedente",
      "cliente_com_historico_de_conflito",
    ],
    firstVersionStatus: "existing",
  },
  {
    id: "strategy",
    name: "Estratégia",
    mission:
      "Transformar contexto do cliente em direção estratégica clara que guia toda a execução da agência.",
    responsibilities: [
      "Diagnóstico de negócio",
      "Definição de posicionamento",
      "Entendimento de público-alvo",
      "Estratégia de conteúdo e territórios",
      "Direção de comunicação",
      "Definição de prioridades",
      "Análise de oferta",
      "Análise competitiva",
      "Identificação de oportunidades de crescimento",
      "Recomendações estratégicas (Strategy Canvas)",
    ],
    permissions: [
      "Acessar Brand Brain completo",
      "Acessar todos os Briefings e handoffs do SDR",
      "Criar e revisar Strategy Canvases",
      "Recomendar departamentos e serviços para acionamento",
      "Propor BrainChangeRequests via governança",
    ],
    forbiddenActions: [
      "Criar criativos finais (posts, designs, anúncios)",
      "Lançar campanhas",
      "Aprovar qualidade de entregas de outros departamentos",
      "Modificar o Brain diretamente",
    ],
    tools: [
      "strategy_engine",
      "strategy_canvas",
      "strategy_room_generator",
      "brand_brain_reader",
      "market_intelligence",
    ],
    suggestedAIEngine: "reasoning",
    allowedKnowledgeSources: [
      "client_brand_brain",
      "briefings",
      "client_requests",
      "strategy_rooms",
      "projects",
      "evidence",
    ],
    qualityGate: [
      "Objetivo principal claro",
      "Público-alvo definido",
      "Posicionamento definido",
      "Diferenciais identificados",
      "Riscos identificados",
      "Oportunidades identificadas",
      "Territórios de conteúdo definidos",
      "Roadmap definido",
    ],
    simulator: "/agency/simulations/strategy",
    trainingCenter: "/agency/strategy",
    evidenceTypes: [
      "strategy_approved",
      "positioning_created",
      "content_territory_defined",
      "roadmap_created",
      "opportunity_identified",
    ],
    humanApprovalTriggers: [
      "aprovação_de_strategy_canvas",
      "mudança_de_posicionamento_estratégico",
      "recomendação_contrária_ao_brief_do_cliente",
    ],
    firstVersionStatus: "existing",
  },
  {
    id: "social-media",
    name: "Social Media",
    mission:
      "Transformar estratégia em execução de conteúdo — o primeiro departamento de execução da agência.",
    responsibilities: [
      "Planejamento editorial",
      "Execução da estratégia de conteúdo",
      "Planejamento de posts",
      "Planejamento de stories",
      "Planejamento de reels",
      "Sequenciamento de conteúdo",
      "Suporte de conteúdo a campanhas",
      "Recomendações de publicação",
      "Otimização de conteúdo",
      "Identificação de oportunidades de engajamento",
    ],
    permissions: [
      "Acessar Brand Brain",
      "Acessar Strategy Canvas aprovado",
      "Criar Social Canvases, planos de conteúdo e calendários editoriais",
      "Propor BrainChangeRequests via governança",
    ],
    forbiddenActions: [
      "Alterar posicionamento",
      "Alterar estratégia",
      "Alterar regras de marca",
      "Alterar regras do Brain",
      "Aprovar Brain Changes",
      "Produzir conteúdo sem estratégia aprovada",
    ],
    tools: [
      "social_engine",
      "social_canvas",
      "content_plan_generator",
      "editorial_calendar",
      "brand_brain_reader",
    ],
    suggestedAIEngine: "creative_copy",
    allowedKnowledgeSources: [
      "client_brand_brain",
      "briefings",
      "strategy_rooms",
      "deliverables",
      "evidence",
    ],
    qualityGate: [
      "Objetivo de conteúdo claro",
      "Territórios de conteúdo definidos",
      "Pilares editoriais definidos",
      "Público-alvo claro",
      "Direção de comunicação clara",
      "Frequência definida",
      "Formatos definidos",
      "Canais definidos",
      "Direção mensal definida",
      "Direção semanal definida",
      "Temas de conteúdo definidos",
      "Indicadores de sucesso definidos",
    ],
    simulator: "/agency/simulations/social",
    trainingCenter: "/agency/social",
    evidenceTypes: [
      "content_plan_created",
      "calendar_generated",
      "territory_executed",
      "engagement_improved",
      "content_approved",
      "content_published",
      "social_strategy_executed",
    ],
    humanApprovalTriggers: [
      "aprovação_de_plano_de_conteúdo",
      "conteúdo_sensível_ou_polémico",
      "publicação_imediata_sem_calendário",
    ],
    firstVersionStatus: "existing",
  },
  {
    id: "design",
    name: "Design",
    mission:
      "Transformar planos de conteúdo em direção visual e briefs criativos — o segundo departamento de execução da agência.",
    responsibilities: [
      "Conceito visual por cliente e segmento",
      "Briefs criativos por tema de conteúdo",
      "Especificações de prompt de imagem para IA",
      "Definição de requisitos de assets visuais",
      "Direção de cor, tipografia e imagem",
      "Regras de consistência de marca",
      "Priorização de produção de assets",
      "Suporte visual a campanhas de tráfego",
      "Manutenção do Brand Brain visual",
      "Aprovação de assets antes de publicação",
    ],
    permissions: [
      "Acessar Brand Brain e Brand Assets",
      "Acessar Social Canvas aprovado",
      "Criar Design Canvases e briefs criativos",
      "Propor BrainChangeRequests via governança",
    ],
    forbiddenActions: [
      "Criar design sem Social Canvas aprovado vinculado",
      "Usar fontes não autorizadas pelo Brand Brain",
      "Alterar posicionamento ou estratégia via design",
      "Criar assets com identidade de marca de terceiros",
      "Publicar sem aprovação do Design Canvas",
      "Prometer prazo de produção sem validação da equipe",
    ],
    tools: [
      "design_engine",
      "design_canvas",
      "creative_brief_generator",
      "image_prompt_spec",
      "brand_brain_reader",
    ],
    suggestedAIEngine: "multimodal",
    allowedKnowledgeSources: [
      "client_brand_brain",
      "brand_assets",
      "briefings",
      "strategy_rooms",
      "social_canvases",
      "deliverables",
      "evidence",
    ],
    qualityGate: [
      "Conceito visual definido",
      "Direção de cor definida",
      "Direção tipográfica definida",
      "Direção de imagem definida",
      "Regras de marca definidas",
      "Briefs criativos gerados",
      "Prompts de imagem gerados",
      "Requisitos de assets definidos",
      "Assets prioritários identificados",
      "Social Canvas vinculado",
    ],
    simulator: "/agency/simulations/design",
    trainingCenter: "/agency/design",
    evidenceTypes: [
      "design_canvas_approved",
      "creative_brief_executed",
      "visual_identity_created",
      "asset_delivered",
      "design_first_round_approval",
    ],
    humanApprovalTriggers: [
      "aprovação_de_design_canvas",
      "identidade_visual_nova",
      "revisao_3_ou_mais_rodadas",
    ],
    firstVersionStatus: "existing",
  },
  {
    id: "paid-traffic",
    name: "Tráfego Pago",
    mission:
      "Transformar estratégia, conteúdo e design em aquisição paga mensurável — o terceiro departamento de execução da agência.",
    responsibilities: [
      "Planejamento de campanhas de mídia paga",
      "Estrutura de campanhas (Meta, Google, YouTube, TikTok, LinkedIn)",
      "Modelo de audiência por segmento e funil",
      "Alocação de budget com fee separado",
      "Mapeamento de ofertas por estágio do funil",
      "Requisitos criativos para campanhas",
      "Projeções de CAC, ROAS e leads",
      "Identificação de riscos de campanha",
      "Análise de performance e otimização",
      "Handoff de resultados para Analytics",
    ],
    permissions: [
      "Acessar Brand Brain e Strategy Canvas",
      "Acessar Social Canvas e Design Canvas aprovados",
      "Criar Traffic Canvases e planos de campanha",
      "Propor BrainChangeRequests via governança",
    ],
    forbiddenActions: [
      "Lançar campanha sem Traffic Canvas aprovado",
      "Usar criativos sem aprovação do Design Canvas",
      "Comprometer budget acima do autorizado no canvas",
      "Combinar management fee com budget de mídia",
      "Alterar posicionamento ou oferta sem aprovação estratégica",
      "Criar campanhas sem objetivo SMART definido",
    ],
    tools: [
      "traffic_engine",
      "traffic_canvas",
      "campaign_structure_generator",
      "audience_model",
      "budget_calculator",
      "brand_brain_reader",
    ],
    suggestedAIEngine: "analytical",
    allowedKnowledgeSources: [
      "client_brand_brain",
      "strategy_rooms",
      "social_canvases",
      "design_canvases",
      "briefings",
      "deliverables",
      "evidence",
    ],
    qualityGate: [
      "Objetivo de campanha claro",
      "Público-alvo definido",
      "Management fee separado do budget de mídia",
      "Campanhas definidas",
      "Canais de mídia definidos",
      "Oferta mapeada",
      "Requisitos criativos definidos",
      "Projeções de resultado definidas",
      "Riscos identificados",
      "Canvas de estratégia vinculado",
    ],
    simulator: "/agency/simulations/traffic",
    trainingCenter: "/agency/traffic",
    evidenceTypes: [
      "traffic_canvas_approved",
      "campaign_launched",
      "leads_generated",
      "roas_achieved",
      "cac_reduced",
    ],
    humanApprovalTriggers: [
      "aprovação_de_traffic_canvas",
      "budget_acima_de_threshold",
      "campanha_para_público_novo",
    ],
    firstVersionStatus: "existing",
  },
  {
    id: "analytics",
    name: "Analytics",
    mission:
      "Transformar dados de performance de todos os departamentos em inteligência mensurável que orienta a tomada de decisão da agência e do cliente.",
    responsibilities: [
      "Framework de KPIs por segmento e objetivo",
      "Modelo de atribuição de canais",
      "Diagnóstico de gaps de performance",
      "Recomendações de otimização cross-departamento",
      "Relatórios de performance e cadência de revisão",
      "Alertas de performance com thresholds definidos",
      "Integração com dados de Strategy, Social, Design e Traffic",
      "Geração de insights acionáveis",
      "Identificação de oportunidades de crescimento",
    ],
    permissions: [
      "Acessar Brand Brain e todos os Canvases aprovados",
      "Criar Analytics Canvases e frameworks de KPIs",
      "Propor BrainChangeRequests via governança",
      "Acessar dados de campanhas e performance",
    ],
    forbiddenActions: [
      "Alterar estratégia sem aprovação do departamento de Estratégia",
      "Lançar campanhas ou criar criativos",
      "Modificar o Brain diretamente",
      "Apresentar dados sem fonte declarada",
    ],
    tools: [
      "analytics_engine",
      "analytics_canvas",
      "kpi_framework_generator",
      "attribution_model",
      "performance_gap_analyzer",
      "brand_brain_reader",
    ],
    suggestedAIEngine: "data_reasoning",
    allowedKnowledgeSources: [
      "client_brand_brain",
      "strategy_rooms",
      "social_canvases",
      "design_canvases",
      "traffic_canvases",
      "deliverables",
      "evidence",
    ],
    qualityGate: [
      "KPI primário definido e mensurável",
      "Modelo de atribuição configurado",
      "Touchpoints de tracking mapeados",
      "Setup de analytics declarado",
      "Gaps de performance identificados",
      "Recomendações com responsável e prazo",
      "Cadência de relatório definida",
      "Insights acionáveis gerados",
      "Thresholds de alerta definidos",
      "Strategy Canvas vinculado",
    ],
    simulator: "/agency/simulations/analytics",
    trainingCenter: "/agency/analytics",
    evidenceTypes: [
      "analytics_canvas_approved",
      "kpi_framework_created",
      "attribution_model_defined",
      "performance_gap_identified",
      "recommendation_executed",
    ],
    humanApprovalTriggers: [
      "aprovação_de_analytics_canvas",
      "mudança_de_modelo_de_atribuição",
      "gap_crítico_de_performance_identificado",
    ],
    firstVersionStatus: "existing",
  },
  {
    id: "project-management",
    name: "Gestão de Projetos",
    mission:
      "Garantir que todos os projetos avancem no pipeline sem bloqueios e com alinhamento total com o cliente.",
    responsibilities: [
      "Criação e atualização de projetos",
      "Envio e acompanhamento de propostas",
      "Geração de tarefas operacionais",
      "Coordenação entre departamentos",
      "Comunicação com clientes",
    ],
    permissions: [
      "Acessar todos os projetos e clientes",
      "Criar e atualizar tarefas",
      "Aprovar passagem de estágio no pipeline",
      "Visualizar estado de todos os departamentos",
    ],
    forbiddenActions: [
      "Aprovar entrega sem revisão do cliente",
      "Iniciar produção sem proposta aprovada",
    ],
    tools: [
      "pm_agent",
      "auto_task_generator",
      "pipeline_engine",
      "timeline_generator",
    ],
    suggestedAIEngine: "operational",
    allowedKnowledgeSources: [
      "client_profile",
      "projects",
      "deliverables",
      "briefings",
      "strategy_rooms",
      "brain_change_requests",
      "quality_reviews",
    ],
    qualityGate: [
      "Task tem dono claro",
      "Prazo definido",
      "Dependências mapeadas",
      "Cliente alinhado antes de passagem de stage",
    ],
    simulator: null,
    trainingCenter: null,
    evidenceTypes: ["delivery_time_reduction", "first_round_approval"],
    humanApprovalTriggers: [
      "proposta_acima_de_threshold",
      "cliente_em_conflito",
      "projeto_parado_mais_de_5_dias",
    ],
    firstVersionStatus: "existing",
  },
  {
    id: "quality",
    name: "Qualidade",
    mission: "Auditar e garantir que o padrão do Brain é respeitado em todas as entregas e handoffs.",
    responsibilities: [
      "Auditar entregas contra Quality Gate global e por departamento",
      "Bloquear entregas que falham nos checks",
      "Identificar padrões de falha para treinamento",
      "Manter o Brain Director informado sobre gaps",
    ],
    permissions: [
      "Acessar todos os departamentos",
      "Bloquear entregas antes de envio ao cliente",
      "Criar alertas de qualidade",
      "Propor BrainChangeRequests",
    ],
    forbiddenActions: [
      "Aprovar entrega sem executar Quality Gate",
      "Ignorar alertas críticos por mais de 24h",
    ],
    tools: [
      "system_doctor",
      "quality_gate_runner",
      "simulation_lab",
    ],
    suggestedAIEngine: "multi_model_audit",
    allowedKnowledgeSources: [
      "deliverables",
      "quality_reviews",
      "training_logs",
      "improvement_suggestions",
      "brain_change_requests",
      "evidence",
    ],
    qualityGate: [
      "Auditoria imparcial — modelo diferente do que gerou o output",
      "Escalação quando necessário — sem omitir problemas",
      "Justificativa registrada em toda rejeição",
    ],
    simulator: "/agency/simulations/quality",
    trainingCenter: "/agency/quality",
    evidenceTypes: ["quality_audit_passed", "quality_gate_blocked", "audit_completed", "pattern_identified"],
    humanApprovalTriggers: ["entrega_crítica_com_risco_legal_ou_financeiro"],
    firstVersionStatus: "existing",
  },
];

export function getBrainDepartment(id: string): BrainDepartment | undefined {
  return BRAIN_DEPARTMENTS.find((d) => d.id === id);
}

export function getBrainDepartmentsByStatus(
  status: BrainDepartment["firstVersionStatus"]
): BrainDepartment[] {
  return BRAIN_DEPARTMENTS.filter((d) => d.firstVersionStatus === status);
}
